my_strings = input(' rfgfg ghgjkg :')
print (len(my_strings))
print (my_strings.upper())
print (my_strings.lower())
print (my_strings.replace(' ',''))
print (my_strings[0])
print (my_strings[-1])
